apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: nginx-rtmp-hls
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - live.pjay.io
      secretName: live-pjay-io
  rules:
    - host: live.pjay.io
      http:
        paths:
        - path: /
          backend:
            serviceName: nginx-hls
            servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp
spec:
  type: LoadBalancer
  ports:
  - name: rtmp
    port: 1935
  selector:
    app: nginx-rtmp-hls
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hls
spec:
  type: NodePort
  ports:
  - name: http 
    port: 80
  selector:
    app: nginx-rtmp-hls
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-rtmp-hls
spec:
  selector:
    matchLabels:
      app: nginx-rtmp-hls
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-rtmp-hls
    spec:
      containers:
      - name: docker-nginx-rtmp-hls
        image: docker.pkg.github.com/teslayana/nginx-rtmp-hls/docker-nginx-rtmp-hls:latest
        ports:
        - containerPort: 80
        - containerPort: 1935
      imagePullSecrets:
      - name: github-packages
