name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login docker.pkg.github.com -u PJay- -p ${{ secrets.GITHUB_TOKEN }}
        docker build -t docker-nginx-rtmp-hls:latest .
        docker push docker.pkg.github.com/pjay-/nginx-rtmp-hls/docker-nginx-rtmp-hls:latest
        
