name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login docker.pkg.github.com -u teslayana -p ${{ secrets.GITHUB_TOKEN }}
        docker build -t docker.pkg.github.com/teslayana/nginx-rtmp-hls/docker-nginx-rtmp-hls .
        docker push docker.pkg.github.com/teslayana/nginx-rtmp-hls/docker-nginx-rtmp-hls
